General:
  seed: 0
  num_devices: -1
  check_val_every_n_epoch: 150 # number of epochs between validation check, needs to be empty (None) for using #batches
  val_check_interval: # number of training batches between each validation check

Model:
  model_type: # either moe or fusion
  classifier: mislnet # 'mislnet' or 'resnet50'
  fusion_rule:
  baseline_ckpt: logs/expert_mislnet_db-real_db-gan_src_q99/version_1/checkpoints/epoch=32-step=120681-v_loss=0.0376-v_acc=0.9874.ckpt # path to the baseline model checkpoint

Data:
  real_dataset_name: dn-real-500 # name of the real dataset
  synthetic_dataset_names: [
    dn-tt,
    dn-sd-500,
  ] # list of tasks to be used for continual learning
  memory_size: 1000 # number of samples to be stored in the memory
  fixed_memory: True # if True, the memory size is fixed