Model:
  model_type: transformer # either moe or fusion or transformer
  load_from_ckpt: True # if True, the ft models are loaded from the checkpoint
  ft_ckpt_paths: [ 
    logs/expert_resnet50_db-real_db-gan_src_q99/version_10/checkpoints/epoch=25-step=12194-v_loss=0.1221-v_acc=0.9588.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-sd14_src_q99/version_25/checkpoints/epoch=149-step=2400-v_loss=0.3378-v_acc=0.8500-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-glide_src_q99/version_8/checkpoints/epoch=149-step=2400-v_loss=0.1350-v_acc=0.9600-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-mj_src_q99/version_6/checkpoints/epoch=149-step=2400-v_loss=0.3947-v_acc=0.8550-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-dallemini_src_q99/version_4/checkpoints/epoch=149-step=2400-v_loss=0.4207-v_acc=0.8450-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-tt_src_q99/version_4/checkpoints/epoch=149-step=2400-v_loss=0.3927-v_acc=0.8350-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-sd21_src_q99/version_4/checkpoints/epoch=149-step=2400-v_loss=0.4361-v_acc=0.8100-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-cips_src_q99/version_4/checkpoints/epoch=149-step=2400-v_loss=0.0932-v_acc=0.9650-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-biggan_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.3329-v_acc=0.8550-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-vqdiff_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.2425-v_acc=0.9300-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-diffgan_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.2260-v_acc=0.9200-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-sg3_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.1910-v_acc=0.9250-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-gansformer_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.0803-v_acc=0.9650-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-dalle2_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.1553-v_acc=0.9350-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-ld_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.6057-v_acc=0.7750-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-eg3d_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.0051-v_acc=0.9950-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-projgan_src_q99/version_2/checkpoints/epoch=149-step=2400-v_loss=0.4599-v_acc=0.8350-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-sd1_src_q99/version_1/checkpoints/epoch=149-step=2400-v_loss=0.3905-v_acc=0.8350-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-ddg_src_q99/version_1/checkpoints/epoch=149-step=2400-v_loss=0.1168-v_acc=0.9650-last.ckpt,
    logs/ft_expert_resnet50_dn-real_dn-ddpm_src_q99/version_1/checkpoints/epoch=149-step=2400-v_loss=0.0888-v_acc=0.9800-last.ckpt,
  ]
  backbone: resnet50 # either resnet50 or mislnet
Data:
  real_dataset_name: dn-real # name of the real dataset
  synthetic_dataset_names: [
    dn-gan,
    dn-sd14,
    dn-glide,
    dn-mj,
    dn-dallemini, dn-tt, dn-sd21, dn-cips, dn-biggan, dn-vqdiff, dn-diffgan, dn-sg3, dn-gansformer, dn-dalle2, dn-ld, dn-eg3d, dn-projgan, dn-sd1, dn-ddg, dn-ddpm,
  ]
  memory_size: 1000 # number of samples to be stored in the memory
  fixed_memory: True # if True, the memory size is fixed

Train:
  epochs: 150
  steps: 2400
  batch_size: 64
  cls_lr: 2.5e-4
  ft_lr: 1.0e-4
  distill: False # if True, the distillation loss is used
  train_dataset_limit_per_class: 25
  train_dataset_limit_real: 25

General:
  check_val_every_n_epoch: 30