Model:
  model_type: transformer # either moe or fusion or transformer
  load_from_ckpt: False # if True, the ft models are loaded from the checkpoint
  ft_ckpt_paths: [
    logs/expert_mislnet_db-real_db-gan_src_q99/version_4/checkpoints/epoch=97-step=183750-v_loss=0.0654-v_acc=0.9763.ckpt
    # logs/expert_resnet50_db-real_db-gan_src_q99/version_1/checkpoints/epoch=50-step=94500-v_loss=0.3354-v_acc=0.8587.ckpt
  ]
  backbone: mislnet # either resnet50 or mislnet
Data:
  real_dataset_name: dn-real # name of the real dataset
  synthetic_dataset_names: [
    dn-gan,
    dn-sd14,
    dn-glide,
    dn-mj,
    dn-dallemini,
    dn-tt,
    dn-sd21,
    dn-cips,
    dn-biggan,
    dn-vqdiff,
    dn-diffgan,
    dn-sg3,
    dn-gansformer,
    dn-dalle2,
    dn-ld,
    dn-eg3d,
    dn-projgan,
    dn-sd1,
    dn-ddg,
    dn-ddpm,
  ]
  memory_size: 1000 # number of samples to be stored in the memory
  fixed_memory: True # if True, the memory size is fixed

Train:
  epochs: 150
  batch_size: 64
  lr: 5.0e-5
  distill: False # if True, the distillation loss is used

General:
  check_val_every_n_epoch: 30